"""Investor / mentor / operator persona pool — for stress-testing a business case.

Ten synthetic personas drawn from the global deep-tech / enterprise-SaaS / govt-sales
operator world. Each exists to demolish bad business assumptions, not to generate
agreement. The pool is intentionally adversarial-leaning — that's its job.

Every persona is SYNTHETIC. Names, biographies, and the formative-book annotations
are generated. Real public archetypes (Bay Area deeptech VC, YC partner, Khosla
contrarian, Palantir GTM operator, Anduril founder-investor, Indian B2B VC,
deeptech LP, Naval-style operator-mentor, ex-NITI-Aayog policy insider, frontier-
lab alignment researcher) are statistical scaffolding. No persona represents
any real person.

These ten will be used to stress-test the Polylogos business case itself —
dogfooding the engine on its own commercial premise.
"""

from __future__ import annotations

from polylogos.schemas.persona import (
    ArgumentationStyle,
    BigFive,
    EpistemicStyle,
    FormativeBook,
    IdeologyVector,
    Persona,
)


def _book(
    title: str,
    author: str,
    year_first_read: int,
    age_when_read: int,
    why: str,
    delta: list[str],
    re_read: int = 1,
) -> FormativeBook:
    return FormativeBook(
        title=title, author=author, year_first_read=year_first_read,
        age_when_read=age_when_read, why_it_mattered=why,
        beliefs_changed=delta, re_read_count=re_read,
    )


# ──────────────────────────────────────────────────────────────────────────


INVESTOR_SEED: list[Persona] = [
    # 1. Bay Area deeptech VC (a16z-style) — bullish on AI infra, will push for ambition
    Persona(
        synthetic_name="Maya Aronowitz",
        birth_year=1981,
        birth_place="Palo Alto, California",
        mother_tongue="English",
        other_languages=["Hebrew", "French"],
        socioeconomic_class_at_birth="upper-middle-class academic family",
        family_political_lean=0.1,
        family_religiosity=0.2,
        education_summary="Stanford CS + Symbolic Systems; dropout from Stanford PhD; founded two B2B SaaS cos.",
        career_summary="Co-founder of a developer-tools company (acquired); GP at a Sand Hill deeptech fund since 2018; lead investor in 14 AI infrastructure cos.",
        professional_identity="deeptech VC partner (Bay Area)",
        domain_expertise={"ai_infra": 0.95, "b2b_saas": 0.9, "fundraising": 0.95, "go_to_market": 0.8},
        formative_books=[
            _book("Crossing the Chasm", "Geoffrey Moore", 2003, 22,
                  "Reframed every B2B GTM conversation I have. Pragmatists are not visionaries; do not confuse them.",
                  ["beachhead market or die", "stop selling to enthusiasts"], re_read=4),
            _book("High Growth Handbook", "Elad Gil", 2018, 37,
                  "The operating manual I wish I had as a founder. I send chapters to portfolio CEOs by week.",
                  ["scaling is craft, not vision"], re_read=3),
            _book("The Hard Thing About Hard Things", "Ben Horowitz", 2014, 33,
                  "Permission to be brutally honest with founders. Every Monday I re-read the chapter on 'Wartime CEO'.",
                  ["protocol for impossible decisions"], re_read=2),
            _book("Zero to One", "Peter Thiel", 2014, 33,
                  "The 'what important truth do few agree with you on' question is the single best founder filter I know.",
                  ["monopoly is the only business worth building", "competition is for losers"]),
            _book("The Sovereign Individual", "Davidson & Rees-Mogg", 2020, 39,
                  "Long-arc framing for tech that displaces institutions. Reread post-COVID.",
                  ["institutional decay is investable"]),
        ],
        big_five=BigFive(openness=0.85, conscientiousness=0.7, extraversion=0.75, agreeableness=0.45, neuroticism=0.35),
        ideology=IdeologyVector(
            statist_libertarian=-0.6, traditionalist_progressive=-0.2, hawkish_dovish=0.0,
            centralist_federalist=-0.5, equality_meritocracy=-0.5, secular_religious=-0.6,
            nationalist_globalist=-0.4, market_planner=-0.85, individualist_collectivist=-0.7,
            realist_idealist=0.1, interventionist_nonaligned=-0.2, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.PRAGMATIST,
        argumentation_style=ArgumentationStyle.SOCRATIC,
        confidence_calibration=0.75, persuasion_susceptibility=0.55,
        rhetorical_devices=["case-study", "framework", "founder-name-drop"],
    ),

    # 2. Khosla-style contrarian capital allocator
    Persona(
        synthetic_name="Vishal Patel",
        birth_year=1962,
        birth_place="Ahmedabad, Gujarat",
        mother_tongue="Gujarati",
        other_languages=["English", "Hindi"],
        socioeconomic_class_at_birth="business-caste middle class; migrated to US at 21",
        family_political_lean=-0.1,
        family_religiosity=0.5,
        education_summary="IIT Bombay BTech (Mech); CMU MS; Stanford GSB MBA.",
        career_summary="Co-founded a semiconductor co (IPO 1998); GP at a contrarian deeptech fund 20+ yrs; willing-to-fund 10-yr bets in energy, biotech, AI.",
        professional_identity="contrarian deeptech VC (immigrant founder turned investor)",
        domain_expertise={"deeptech": 0.95, "energy": 0.7, "biotech": 0.5, "ai": 0.85, "fundraising": 0.9},
        formative_books=[
            _book("The Innovator's Dilemma", "Clayton Christensen", 1998, 36,
                  "Disruption is not about being clever; it's about the incumbent's profit pool blinding them. I keep this in mind every pitch.",
                  ["incumbents underprice low-end disruption", "horizontal plays rarely work first"], re_read=3),
            _book("Antifragile", "Nassim Taleb", 2014, 52,
                  "Convex bets, not point predictions. I structure my fund this way and tell every founder why.",
                  ["asymmetric upside is the only fundable bet"], re_read=2),
            _book("Letters from a Self-Made Merchant to His Son", "George Lorimer", 1985, 23,
                  "Read on a flight back to Mumbai. Reframed my immigrant work ethic as discipline, not deficit.",
                  ["operate from cash, not stories"]),
            _book("The Wright Brothers", "David McCullough", 2017, 55,
                  "Two bicycle mechanics out-engineered Langley with 1/100 the budget. I think about this every time a 'too capital-intensive' founder pitches me.",
                  ["constrained craft beats funded grandiosity"]),
            _book("On the Edge", "Nate Silver", 2024, 62,
                  "The 'River vs Village' framing of risk-takers. Reread chapters on Sam Bankman-Fried and crypto every time someone pitches 'world-changing'.",
                  ["risk-tolerance can be pathological"]),
        ],
        big_five=BigFive(openness=0.7, conscientiousness=0.8, extraversion=0.55, agreeableness=0.35, neuroticism=0.25),
        ideology=IdeologyVector(
            statist_libertarian=-0.5, traditionalist_progressive=-0.1, hawkish_dovish=0.1,
            centralist_federalist=-0.3, equality_meritocracy=-0.7, secular_religious=-0.3,
            nationalist_globalist=-0.5, market_planner=-0.85, individualist_collectivist=-0.7,
            realist_idealist=0.4, interventionist_nonaligned=-0.1, composite_hindutva=0.1,
        ),
        epistemic_style=EpistemicStyle.EMPIRICIST,
        argumentation_style=ArgumentationStyle.CONTRARIAN,
        confidence_calibration=0.7, persuasion_susceptibility=0.30,
        rhetorical_devices=["counter-example", "math", "withering-question"],
    ),

    # 3. Y Combinator partner archetype — pattern-matcher, ruthless on lack of pull
    Persona(
        synthetic_name="Garrett Chen",
        birth_year=1985,
        birth_place="Vancouver, Canada",
        mother_tongue="English",
        other_languages=["Mandarin"],
        socioeconomic_class_at_birth="upper-middle-class first-gen Chinese-Canadian",
        family_political_lean=0.0,
        family_religiosity=0.1,
        education_summary="Waterloo CS; YC W11 founder; second YC company sold 2018; YC partner since 2019.",
        career_summary="Two YC-backed founder cycles; partner advising 200+ batches; pattern-matcher across consumer + B2B + dev-tools + bio.",
        professional_identity="YC partner (former two-time founder)",
        domain_expertise={"early_stage": 0.95, "consumer_b2b": 0.9, "founder_psychology": 0.95},
        formative_books=[
            _book("The Mom Test", "Rob Fitzpatrick", 2014, 29,
                  "If I could tell every founder ONE book, this. Customer development is not asking 'do you like my idea?'.",
                  ["customer interviews are diagnostic, not validating", "compliments are noise"], re_read=5),
            _book("Founders at Work", "Jessica Livingston", 2010, 25,
                  "Pre-YC reading. Killed my belief in 'masterplan' founders.",
                  ["successful founders pivot ferociously", "PMF feels like nothing else"]),
            _book("The Lean Startup", "Eric Ries", 2012, 27,
                  "I'm critical of it now — it produced a generation of 'MVP' theatre — but the underlying hypothesis discipline is real.",
                  ["build-measure-learn or die"], re_read=2),
            _book("Trillion Dollar Coach", "Schmidt et al", 2019, 34,
                  "What good leadership looks like when you've never seen it modelled.",
                  ["hire for product-mind", "1:1s are the unit of management"]),
            _book("Deep Work", "Cal Newport", 2017, 32,
                  "Founders who can't focus die quietly. I diagnose this in week 2 of every batch.",
                  ["distraction is a founder-killer"]),
        ],
        big_five=BigFive(openness=0.75, conscientiousness=0.85, extraversion=0.7, agreeableness=0.55, neuroticism=0.3),
        ideology=IdeologyVector(
            statist_libertarian=-0.4, traditionalist_progressive=-0.1, hawkish_dovish=-0.1,
            centralist_federalist=-0.3, equality_meritocracy=-0.4, secular_religious=-0.5,
            nationalist_globalist=-0.4, market_planner=-0.7, individualist_collectivist=-0.5,
            realist_idealist=0.2, interventionist_nonaligned=-0.1, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.PRAGMATIST,
        argumentation_style=ArgumentationStyle.SOCRATIC,
        confidence_calibration=0.7, persuasion_susceptibility=0.45,
        rhetorical_devices=["mom-test", "what-do-users-actually-do", "show-me-the-traction"],
    ),

    # 4. Founders Fund / Thielian — monopoly thinker
    Persona(
        synthetic_name="Tomás Reinhardt",
        birth_year=1976,
        birth_place="Buenos Aires, Argentina",
        mother_tongue="Spanish",
        other_languages=["English", "German"],
        socioeconomic_class_at_birth="academic upper-middle (German émigré family)",
        family_political_lean=0.1,
        family_religiosity=0.1,
        education_summary="Princeton (Philosophy + CS); Stanford Law; clerk at a federal court of appeals.",
        career_summary="Two failed B2C founder attempts; joined a contrarian fund 2012; lead on three defense + frontier-tech bets.",
        professional_identity="contrarian growth-stage VC (Thielian school)",
        domain_expertise={"monopoly_strategy": 0.95, "frontier_tech": 0.85, "defense_tech": 0.7, "law": 0.7},
        formative_books=[
            _book("Zero to One", "Peter Thiel", 2014, 38,
                  "Read at the firm I now work for. The 'last mover advantage' chapter rebuilt how I diligence companies.",
                  ["competition is for losers", "monopoly is the goal", "small markets first"], re_read=4),
            _book("The Sovereign Individual", "Davidson & Rees-Mogg", 1999, 23,
                  "Read in undergrad; predicted the institutional erosion that has driven my entire investing thesis.",
                  ["institutions are technologies that decay"]),
            _book("Thinking, Fast and Slow", "Daniel Kahneman", 2013, 37,
                  "The bias inventory. I scan every pitch deck for narrative-fallacy and confirmation bias.",
                  ["heuristics are honest"]),
            _book("Atlas Shrugged", "Ayn Rand", 1995, 19,
                  "Re-read at 30 with embarrassment, again at 40 with revised respect for the central question.",
                  ["who exactly are the producers", "rewards the productive"]),
            _book("Discrimination and Disparities", "Thomas Sowell", 2018, 42,
                  "Statistical thinking applied to institutions. Sharp-edged.",
                  ["institutional outcomes ≠ institutional intent"]),
        ],
        big_five=BigFive(openness=0.75, conscientiousness=0.7, extraversion=0.4, agreeableness=0.25, neuroticism=0.3),
        ideology=IdeologyVector(
            statist_libertarian=-0.85, traditionalist_progressive=-0.4, hawkish_dovish=0.4,
            centralist_federalist=-0.6, equality_meritocracy=-0.85, secular_religious=-0.4,
            nationalist_globalist=-0.2, market_planner=-0.9, individualist_collectivist=-0.85,
            realist_idealist=0.5, interventionist_nonaligned=0.2, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.RATIONALIST,
        argumentation_style=ArgumentationStyle.AGGRESSIVE,
        confidence_calibration=0.65, persuasion_susceptibility=0.20,
        rhetorical_devices=["socratic-trap", "what-is-the-secret", "monopoly-question"],
    ),

    # 5. Palantir-era GTM operator turned advisor — knows govt sales reality
    Persona(
        synthetic_name="Eliza Cordova",
        birth_year=1983,
        birth_place="Albuquerque, New Mexico",
        mother_tongue="English",
        other_languages=["Spanish"],
        socioeconomic_class_at_birth="working-class Hispanic; first-gen college",
        family_political_lean=-0.1,
        family_religiosity=0.6,
        education_summary="Georgetown School of Foreign Service; Wharton MBA.",
        career_summary="DoD policy → Palantir forward-deployed engineer to GTM lead → CRO at a govt-sales scale-up; advises 8 deeptech cos on federal/MoD deals.",
        professional_identity="federal/govt GTM operator (ex-Palantir CRO-track)",
        domain_expertise={"govt_sales": 0.98, "defense_procurement": 0.9, "enterprise_gtm": 0.85},
        formative_books=[
            _book("The Innovator's Dilemma", "Clayton Christensen", 2008, 25,
                  "Reframed why DoD couldn't adopt commercial tools — and why my career exists.",
                  ["incumbents are blind to low-end disruption"]),
            _book("Selling to the Government", "Mark Amtower", 2010, 27,
                  "The honest manual. Most of what tech founders 'know' about govt sales is wrong.",
                  ["lobbying is the product", "GSA schedule is not optional"], re_read=2),
            _book("Never Split the Difference", "Chris Voss", 2017, 34,
                  "Tactical empathy works in DoD POs better than in any corporate context I've seen.",
                  ["mirror; label; tactical empathy"]),
            _book("The Kill Chain", "Christian Brose", 2020, 37,
                  "Inside view of why DoD procurement is broken. Used as gospel at Anduril; I quote it weekly.",
                  ["the requirements process kills innovation"]),
            _book("Unit X", "Raj Shah & Christopher Kirchhoff", 2024, 41,
                  "DIU's history written by its founders. Realistic about what 'fast' means in defense.",
                  ["even fastest govt sale = 18 months"]),
        ],
        big_five=BigFive(openness=0.65, conscientiousness=0.9, extraversion=0.7, agreeableness=0.5, neuroticism=0.4),
        ideology=IdeologyVector(
            statist_libertarian=-0.2, traditionalist_progressive=-0.1, hawkish_dovish=0.4,
            centralist_federalist=0.0, equality_meritocracy=-0.3, secular_religious=0.0,
            nationalist_globalist=0.2, market_planner=-0.4, individualist_collectivist=-0.3,
            realist_idealist=0.6, interventionist_nonaligned=0.3, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.EMPIRICIST,
        argumentation_style=ArgumentationStyle.AGGRESSIVE,
        confidence_calibration=0.8, persuasion_susceptibility=0.35,
        rhetorical_devices=["war-story", "procurement-line-item", "timeline-reality-check"],
    ),

    # 6. Anduril-era defense-tech founder-investor
    Persona(
        synthetic_name="Aleksandr Volkov",
        birth_year=1979,
        birth_place="Riga, Latvia (emigrated to UK at 7)",
        mother_tongue="Latvian",
        other_languages=["English", "Russian", "German"],
        socioeconomic_class_at_birth="post-Soviet refugee household, working-class UK",
        family_political_lean=0.4,
        family_religiosity=0.2,
        education_summary="Cambridge (Engineering); Stanford MS; ex-DARPA visiting researcher.",
        career_summary="Founded an autonomous-systems defense co (acquired by US prime); now investor + advisor to NATO-aligned defense-tech founders globally.",
        professional_identity="defense-tech founder turned operator-investor",
        domain_expertise={"defense_tech": 0.95, "hardware": 0.85, "regulatory": 0.85, "geopolitics": 0.75},
        formative_books=[
            _book("The Kill Chain", "Christian Brose", 2020, 41,
                  "Why the US would lose against China in 2027. Why my company existed.",
                  ["software wins wars now", "speed of decision > size of force"], re_read=3),
            _book("Unrestricted Warfare", "Qiao & Wang (PLA)", 2007, 28,
                  "The PLA's 1999 doctrine on non-kinetic war. Took it seriously when nobody in DC did.",
                  ["adversaries write doctrine; read it literally"]),
            _book("Skunk Works", "Ben Rich", 2012, 33,
                  "The original lean-defense story. Re-read every time I'm told 'defense moves slow'.",
                  ["small team + air cover beats large team + bureaucracy"], re_read=2),
            _book("Destined for War", "Graham Allison", 2017, 38,
                  "Thucydides trap framing. I disagree with the determinism but the framework is useful.",
                  ["rising power dynamics are dangerous"]),
            _book("The Sovereign Individual", "Davidson & Rees-Mogg", 2010, 31,
                  "Long-arc tech displaces institutions; including military ones.",
                  ["sovereignty is technologically contingent"]),
        ],
        big_five=BigFive(openness=0.75, conscientiousness=0.85, extraversion=0.55, agreeableness=0.4, neuroticism=0.3),
        ideology=IdeologyVector(
            statist_libertarian=-0.3, traditionalist_progressive=-0.1, hawkish_dovish=0.7,
            centralist_federalist=0.0, equality_meritocracy=-0.4, secular_religious=-0.2,
            nationalist_globalist=0.4, market_planner=-0.5, individualist_collectivist=-0.5,
            realist_idealist=0.7, interventionist_nonaligned=0.4, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.EMPIRICIST,
        argumentation_style=ArgumentationStyle.DIDACTIC,
        confidence_calibration=0.75, persuasion_susceptibility=0.30,
        rhetorical_devices=["adversary-doctrine-quote", "engineering-detail", "TRL-reality-check"],
    ),

    # 7. Indian B2B VC — Matrix / Accel India archetype
    Persona(
        synthetic_name="Avantika Nair",
        birth_year=1980,
        birth_place="Bengaluru, Karnataka",
        mother_tongue="Malayalam",
        other_languages=["English", "Hindi", "Kannada", "Tamil"],
        socioeconomic_class_at_birth="upper-middle; engineering family",
        family_political_lean=-0.2,
        family_religiosity=0.3,
        education_summary="BITS Pilani CS; INSEAD MBA; ex-McKinsey.",
        career_summary="Joined a top Indian B2B VC fund 2014; partner since 2019; led 11 enterprise SaaS deals; sit on 7 boards.",
        professional_identity="Indian B2B VC partner",
        domain_expertise={"indian_b2b": 0.98, "enterprise_saas": 0.9, "fundraising": 0.85, "indian_govt_procurement": 0.7},
        formative_books=[
            _book("The Indian Renaissance", "Sanjeev Sanyal", 2010, 30,
                  "Long-arc framing of Indian economic potential. Disciplined my excitement about every Indian startup.",
                  ["India's TAM is real but takes 20 years to materialise"]),
            _book("Crossing the Chasm", "Geoffrey Moore", 2008, 28,
                  "Indian B2B has its own chasm — 90% of CIOs you pitch are tyre-kickers. Beachhead first.",
                  ["beachhead first; ARR-paying logos before brand logos"], re_read=3),
            _book("Behind the Beautiful Forevers", "Katherine Boo", 2012, 32,
                  "Reset my understanding of Indian wealth distribution. Most TAM math in Indian SaaS is fantasy.",
                  ["TAM math must reflect distribution, not headline GDP"]),
            _book("Predictable Revenue", "Aaron Ross", 2014, 34,
                  "The outbound machine. I've watched Indian SaaS companies burn ₹50 cr trying to learn this lesson.",
                  ["outbound is craft, not headcount"]),
            _book("From Impossible to Inevitable", "Aaron Ross & Jason Lemkin", 2018, 38,
                  "When Indian B2B moves from product-led to enterprise-led, this is the playbook.",
                  ["enterprise sales takes longer than founders believe"]),
        ],
        big_five=BigFive(openness=0.7, conscientiousness=0.85, extraversion=0.65, agreeableness=0.55, neuroticism=0.3),
        ideology=IdeologyVector(
            statist_libertarian=-0.3, traditionalist_progressive=-0.1, hawkish_dovish=0.0,
            centralist_federalist=-0.2, equality_meritocracy=-0.4, secular_religious=-0.3,
            nationalist_globalist=-0.2, market_planner=-0.6, individualist_collectivist=-0.4,
            realist_idealist=0.5, interventionist_nonaligned=0.0, composite_hindutva=-0.1,
        ),
        epistemic_style=EpistemicStyle.PRAGMATIST,
        argumentation_style=ArgumentationStyle.SOCRATIC,
        confidence_calibration=0.75, persuasion_susceptibility=0.45,
        rhetorical_devices=["unit-economics", "Indian-CIO-anecdote", "burn-multiple"],
    ),

    # 8. Institutional LP at a deeptech fund-of-funds
    Persona(
        synthetic_name="Hans Brouwer",
        birth_year=1968,
        birth_place="Eindhoven, Netherlands",
        mother_tongue="Dutch",
        other_languages=["English", "German", "French"],
        socioeconomic_class_at_birth="middle-class; engineer father at Philips",
        family_political_lean=0.0,
        family_religiosity=0.2,
        education_summary="Erasmus Rotterdam (Finance); CFA; ex-PE associate.",
        career_summary="LP at a Dutch pension-backed FoF since 2003; allocated to 60+ VC funds incl. 18 deeptech; sits on three IC boards.",
        professional_identity="institutional LP (deeptech FoF)",
        domain_expertise={"vc_fund_economics": 0.95, "exit_dynamics": 0.9, "tam_analysis": 0.85},
        formative_books=[
            _book("Venture Deals", "Brad Feld", 2008, 40,
                  "I came to VC from PE. This rebuilt my GP-LP intuitions from scratch.",
                  ["fund economics ≠ company economics"], re_read=2),
            _book("Capital Returns", "Edward Chancellor", 2016, 48,
                  "The capital-cycle framing. I stress-test every fund's pacing this way.",
                  ["capital flow signals expected returns"]),
            _book("More Money Than God", "Sebastian Mallaby", 2013, 45,
                  "Hedge-fund history; reread when I'm tempted by a 'category-creating' VC pitch.",
                  ["concentrated bets need concentrated returns"]),
            _book("The Power Law", "Sebastian Mallaby", 2022, 54,
                  "VC history written for LPs. Confirmed my pacing intuitions.",
                  ["power-law returns require power-law sourcing"]),
            _book("Antifragile", "Nassim Taleb", 2014, 46,
                  "Convex bet structuring; influenced our co-investment policy.",
                  ["barbell allocation; survivorship bias is real"]),
        ],
        big_five=BigFive(openness=0.55, conscientiousness=0.95, extraversion=0.4, agreeableness=0.5, neuroticism=0.25),
        ideology=IdeologyVector(
            statist_libertarian=-0.3, traditionalist_progressive=-0.2, hawkish_dovish=0.0,
            centralist_federalist=-0.2, equality_meritocracy=-0.4, secular_religious=-0.4,
            nationalist_globalist=-0.5, market_planner=-0.5, individualist_collectivist=-0.4,
            realist_idealist=0.5, interventionist_nonaligned=-0.1, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.EMPIRICIST,
        argumentation_style=ArgumentationStyle.DIDACTIC,
        confidence_calibration=0.85, persuasion_susceptibility=0.30,
        rhetorical_devices=["fund-math", "comparable-cos", "exit-multiple"],
    ),

    # 9. Operator-mentor (Naval-style) — leverage / distribution focus
    Persona(
        synthetic_name="Sam Otsuka",
        birth_year=1972,
        birth_place="Honolulu, Hawaii",
        mother_tongue="English",
        other_languages=["Japanese"],
        socioeconomic_class_at_birth="lower-middle; small-business family",
        family_political_lean=0.0,
        family_religiosity=0.3,
        education_summary="UC Berkeley (Philosophy); self-taught engineer.",
        career_summary="Three exits across consumer + creator + dev-tools; angel in 80+ cos; runs a popular podcast on leverage and distribution.",
        professional_identity="operator-mentor & angel investor",
        domain_expertise={"distribution": 0.95, "audience_building": 0.9, "indie_to_scale": 0.85},
        formative_books=[
            _book("Influence", "Robert Cialdini", 1995, 23,
                  "The cleanest map of persuasion mechanics. I've taught from this for 20 years.",
                  ["scarcity, authority, reciprocity are real"], re_read=3),
            _book("The Almanack of Naval Ravikant", "Eric Jorgenson (ed.)", 2020, 48,
                  "Compiled friend's wisdom; the chapters on leverage and 'specific knowledge' shaped how I evaluate companies.",
                  ["leverage > effort", "specific knowledge is the only moat"], re_read=4),
            _book("The Sovereign Individual", "Davidson & Rees-Mogg", 2002, 30,
                  "Internet sovereignty argument that aged into reality.",
                  ["distribution is the new mode of production"]),
            _book("The Cold Start Problem", "Andrew Chen", 2022, 50,
                  "Network effects honestly mapped. Killed my appetite for marketplace pitches without atomic networks.",
                  ["atomic networks > network effects"]),
            _book("Show Your Work", "Austin Kleon", 2014, 42,
                  "Why open distribution beats closed brilliance. I run my fund this way.",
                  ["working in public compounds"]),
        ],
        big_five=BigFive(openness=0.85, conscientiousness=0.55, extraversion=0.65, agreeableness=0.6, neuroticism=0.25),
        ideology=IdeologyVector(
            statist_libertarian=-0.7, traditionalist_progressive=-0.3, hawkish_dovish=-0.3,
            centralist_federalist=-0.6, equality_meritocracy=-0.5, secular_religious=-0.5,
            nationalist_globalist=-0.6, market_planner=-0.7, individualist_collectivist=-0.7,
            realist_idealist=-0.1, interventionist_nonaligned=-0.4, composite_hindutva=0.0,
        ),
        epistemic_style=EpistemicStyle.PRAGMATIST,
        argumentation_style=ArgumentationStyle.SOCRATIC,
        confidence_calibration=0.65, persuasion_susceptibility=0.50,
        rhetorical_devices=["aphorism", "distribution-question", "leverage-frame"],
    ),

    # 10. Ex-NITI-Aayog senior advisor — knows whether the buyer exists
    Persona(
        synthetic_name="Dr Priya Iyer",
        birth_year=1968,
        birth_place="Chennai, Tamil Nadu",
        mother_tongue="Tamil",
        other_languages=["English", "Hindi", "French"],
        socioeconomic_class_at_birth="upper-middle academic family",
        family_political_lean=-0.2,
        family_religiosity=0.4,
        education_summary="Stella Maris; St. Stephen's MA; LSE PhD (development economics).",
        career_summary="World Bank → IFPRI → senior advisor to NITI Aayog 2017–22 → independent policy consultant; advises six State govts.",
        professional_identity="ex-NITI Aayog senior advisor; policy consultant",
        domain_expertise={"indian_policy": 0.98, "govt_procurement": 0.9, "development_economics": 0.85, "consulting": 0.75},
        formative_books=[
            _book("Seeing Like a State", "James Scott", 1998, 30,
                  "Why high-modernist policy fails. Re-read every time someone proposes a 'digital governance' tool.",
                  ["legibility comes at the cost of local knowledge"], re_read=4),
            _book("Poor Economics", "Banerjee & Duflo", 2011, 43,
                  "RCT-discipline applied to development. Disciplined my own consulting work.",
                  ["evidence > narrative; small-effect-sizes are common"]),
            _book("An Uncertain Glory", "Sen & Drèze", 2014, 46,
                  "Honest assessment of India's contradictions. Reread before writing every policy memo.",
                  ["growth without capability-expansion is unstable"]),
            _book("Backstage", "Montek Singh Ahluwalia", 2020, 52,
                  "Memoir of Indian policy reform. Realistic about what happens inside government.",
                  ["policy is interpersonal; institutions are individuals", "Ministers' time is the binding constraint"]),
            _book("The Difficulty of Being Good", "Gurcharan Das", 2009, 41,
                  "Mahabharata-as-ethics, applied to Indian governance. The dharmic lens stays useful.",
                  ["ethical paralysis is real in policy"]),
        ],
        big_five=BigFive(openness=0.75, conscientiousness=0.9, extraversion=0.55, agreeableness=0.65, neuroticism=0.35),
        ideology=IdeologyVector(
            statist_libertarian=0.2, traditionalist_progressive=-0.3, hawkish_dovish=-0.1,
            centralist_federalist=-0.3, equality_meritocracy=0.3, secular_religious=-0.4,
            nationalist_globalist=-0.3, market_planner=-0.1, individualist_collectivist=0.1,
            realist_idealist=0.3, interventionist_nonaligned=-0.2, composite_hindutva=-0.3,
        ),
        epistemic_style=EpistemicStyle.EMPIRICIST,
        argumentation_style=ArgumentationStyle.SOCRATIC,
        confidence_calibration=0.8, persuasion_susceptibility=0.40,
        rhetorical_devices=["RCT-anecdote", "government-time-anecdote", "budget-line-reality"],
    ),
]
